exodus = {
"1": "Suffering",
"2": "Moses",
"3": "Calling",
"4": "Return",
"5": "Meeting Pharaoh",
"6": "Promise",
"7": "Blood",
"8": "f-g-f(frogs, gnats, flies)",
"9": "p-b-h(pestilence, boils, hail)",
"10": "l-d (locusts, darkness)",
"11": "Death of Firstborn",
"12": "Passover",
"13": "Escape",
"14": "Crossing the Red Sea",
"15": "Song of Deliverance/Bitter Water",
"16": "Manna",
"17": "Amalekites/Meribah I",
"18": "Jethro/Delegation",
"19": "Sinai Covenant",
"20": "Ten Commandments",
"21": "Laws concerning Life",
"22": "Laws concerning Properties",
"23": "Laws concerning Feasts",
"24": "Covenant Wedding Ceremony",
"25": "a-t-g (ark, table of the bread of prescence, golden lampstand)",
"26": "Veil",
"27": "Altar",
"28": "Priestly garments",
"29": "Priestly Regulations",
"30": "Basin",
"31": "Skilled Workers",
"32": "Golden Calf",
"33": "Intercession",
"34": "Second Ten Commandments",
"35": "Offering",
"36": "Construction begins",
"37": "a-t-g-i (ark, table of the bread of prescence, golden lampstand, golden altar of inscence)",
"38": "a-b (altar / basin)",
"39": "Completion of priestly garments/ Completion of Tabernacle",
"40": "Dedication"
}
