first_kings = {
    "1" : "King Solomon",
    "2" : "Purge",
    "3" : "Solomon's wisdom",
    "4" : "Prosperity 1",
    "5" : "Preparation for Temple Construction",
    "6" : "Temple construction begins",
    "7" : "Construction of palace, temple furnishings",
    "8" : "Entrance of the ark of the covenant",
    "9" : "Solomonic covenant",
    "10" : "Prosperity 2 (Queen of Sheba)",
    "11" : "Fall and death of Solomon",
    "12" : "Divided kingdom - Rehoboam / Jeroboam",
    "13" : "Bethel - Dan incense altars (Old prophet / young prophet)",
    "14" : "Shishak invasion",
    "15a" : "Nadab, Baasha",
    "15b" : "Abijah(m), Asa, Jehoshaphat",
    "16" : "Elah, Zimri, Omri, Ahab (Elijah's ministry)",
    "17a" : "Elijah @ Cherith Brook",
    "17b" : "Elijah @ Zarephath",
    "18" : "Elijah @ Mt. Carmel",
    "19" : "Elijah @ Mt. Horeb",
    "20" : "Wars with Aram(Syria) 1&2",
    "21" : " Naboth's vineyard",
    "22" : "Death of Ahab"
}