first_chronicles = {
        "1": "Genealogy of Adam",
        "2": "Genealogy of Judah",
        "3": "Genealogy of David",
        "4": "Southern Tribes",
        "5": "Eastern Tribes",
        "6": "Levites",
        "7": "Northern Tribes",
        "8": "Tribe of Benjamin",
        "9": "List of returned exiles",
        "10": "Death of Saul",
        "11": "King David",
        "12": "Mighty Men of David",
        "13": "Death of Uzzah",
        "14": "David's fame",
        "15": "Entrance of the ark of covenant",
        "16": "David's prayer of thanksgiving",
        "17": "Prayer and covenant",
        "18": "Early victories of war",
        "19": "Late victories of war",
        "20": "Ammonite War",
        "21": "Census",
        "22": "Preparation of Temple Construction",
        "23": "Duties of Levites",
        "24": "Duties of Priests",
        "25": "Duties of Musicians",
        "26": "Duties of Gatekeepres",
        "27": "Military and administrative organization",
        "28": "David's charge to build temple to Solomon",
        "29": "Offering for Temple construction"
            }