first_samuel = {
    "1": "Hannah's prayer",
    "2": "Samuel / Eli's sin",
    "3": "Calling of Samuel",
    "4": "Capture of the Ark",
    "5": "Plagues of the Ark",
    "6": "Return of the Ark",
    "7": "Mizpah revival",
    "8": "Request for a king",
    "9": "Meeting of Saul and Samuel",
    "10": "Anointing of Saul",
    "11": "Ammonite War",
    "12": "Samuel's farewell sermon",
    "13": "Saul's foolish sacrifice",
    "14": "Jonathan's victory by faith",
    "15": "Saul's disobedience (1 Sam. 15:22)",
    "16": "Anointing of David (1 Sam. 16:7)",
    "17": "David killed Goliath",
    "18": "Jealousy 1, Meeting of David and Jonathan",
    "19": "Jealousy 2",
    "20": "Friendship of David and Jonathan",
    "21": "Escape to Nob (cf. Matt. 12)",
    "22": "Adullam 400",
    "23": "Saving Keilah",
    "24": "Corner of Saul's robe",
    "25": "Marriage to Abigail, Samuel's death",
    "26": "Saul's spear and water jug",
    "27": "Receiving Ziklag",
    "28": "Medium of Endor",
    "29": "David was distrusted",
    "30": "Revenge against the Amalekites",
    "31": "Death of Saul"
}