matthew = {
"1": "Geneology and birth of Jesus",
"2": "Magi and Herod ",
"3": "Baptism of Jesus / John the Baptist",
"4": "Temptations of Jesus",
"5": "Beatitudes (Poor in Spirit, Mourn, Meek, Hunger and thirst for righteousness, Merciful, Pure in heart, peacemakers, persecuted",
"6": "a-p-f(alms, prayer, fasting",
"7": "a-s-k (ask, seek, knock",
"8": "c-s-l(a = centurion, b = storm, c = legion",
"9": "b-p-b(bleeding woman, paralytic, blind",
"10": "12 Disciples (Peter, Andrew, James, John, Philip, Bartholomew, Thomas, Matthew, James, Thaddeus, Simon, and Judas",
"11": "k-i (kingdom invasion",
"12": "Sabbath",
"13": "p-k (parables of the kingdom",
"14": "5-2, w-o-w (5 loaves and two fish, walking on water",
"15": "7-2 (seven loaves and two fish",
"16": "Peter's confession",
"17": "the Transfiguration",
"18": "Little children",
"19": "Rich young ruler",
"20": "11th hour workers",
"21": "Entering Jerusalem",
"22": "the greatest commandment",
"23": "seven woes",
"24": "e-t-s(end time signs",
"25": "t-v (talents, virgins",
"26": "arrest, Peter's denial",
"27": "Death on the cross",
"28": "Resurrection / Great Commission"
}
