second_chronicles = {
        "1": "Solomon's Wisdom",
        "2": "Preperation for Temple construction",
        "3": "Temple construction begins",
        "4": "Temple furnishings",
        "5": "Entrance of the ark of the covenant",
        "6": "Solomon's dedication prayer and thanksgiving",
        "7": "Dedication of Temple and feast of Tabernacles",
        "8": "Prosperity",
        "9": "Death of Saul",
        "10": "Divided kingdom - Rehoboam",
        "11": "Rehoboam strengthens kingdom",
        "12": "Shishak invasion",
        "13": "Abijah(m)",
        "14": "Reign of Asa",
        "15": "Asa's reforms",
        "16": "Hanani rebukes Asa (verse 9)",
        "17": "Jehoshaphat's reforms",
        "18": "Death of Ahab",
        "19": "Jehu (son of Hanani) rebukes Jehosahaphat",
        "20": "Jehoshaphat's prayer",
        "21": "Jehoram",
        "22": "Ahaziah",
        "23": "Athaliah",
        "24": "Joash",
        "25": "Amaziah",
        "26": "Uzziah",
        "27": "Jotham",
        "28": "Ahaz",
        "29": "Hezekiah cleanses temple",
        "30": "Hezekiah's passover",
        "31": "Hezekiah's reforms",
        "32": "Death of Hezekiah",
        "33": "Manasseh, Amon",
        "34": "Josiah's reforms",
        "35": "Josiah's passover",
        "36": "Jehoahaz, Jehoiakim, Jehoiachin, Zedekiah"
            }