second_samuel = {
    "1": "David's lament",
    "2": "King of Judah at Hebron",
    "3": "Death of Abner",
    "4": "Death of Ish-bosheth",
    "5": "King of United Monarchy in Jerusalem",
    "6": "Entrance of the Ark",
    "7": "Davidic Covenant",
    "8": "Military victories",
    "9": "Mephibosheth at king's table",
    "10": "Ammonite War",
    "11": "Bathsheba",
    "12": "Nathan's rebuke and David's repentance",
    "13": "Break-up of the family",
    "14": "Absalom's escape and return",
    "15": "Absalom's mutiny",
    "16": "Shimei curses David",
    "17": "Two strategies (Hushai vs Ahithophel)",
    "18": "Death of Absalom",
    "19": "Return of David",
    "20": "Sheba's mutiny",
    "21": "Avenging the Gibeonites",
    "22": "David's testimony",
    "23": "David's last words",
    "24": "Census (sin), Araunah's threshing floor"
}