second_kings = {
    "1" : "Ahaziah",
    "2" : "Ascension of Elijah (chariot of fire)",
    "3" : "Jehoram",
    "4" : "Elisha and 2 women",
    "5" : "Naaman",
    "6" : " Horses and chariots of fire",
    "7" : "4 lepers",
    "8.N." : "Shunammite woman whose land was restored",
    "8.S." : "Jerhoram, Ahaziah",
    "9" : "Jehu",
    "10" : "Jehu's purge",
    "11" : "Athaliah(evil queen)",
    "12" : "Jehoash(Joash)",
    "13" : "Jehoahaz, Joash",
    "14.N." : "Jeroboam 2",
    "14.S." : "Amaziah",
    "15.N." : "Zechariah, Shallum, Menahem, Pekahiah, Peka",
    "15.S." : "Uzziah, Jotham",
    "16" : "Ahaz",
    "17" : " Hoshea(last king of Israel)",
    "18" : "Hezekiah",
    "19" : "Hezekiah's prayer",
    "20" : "Hezekiah's illness",
    "21" : "Manasseh, Ammon",
    "22" : "Josiah(Book of the Law found)",
    "23a" : "Josiah's reforms",
    "23b" : "Jehoahaz",
    "24" : "Jehoiakim, Jehoiachin, Zedekiah",
    "25" : "Fall of Judah 586 B.C. by Babylonians"
}